package com.aura.what2eat.ui.screens

import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Block
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.aura.what2eat.auth.AuthResult
import com.aura.what2eat.auth.GoogleAuthManager
import com.aura.what2eat.model.CommunityDish
import com.aura.what2eat.model.CuisineType
import com.aura.what2eat.model.Dish
import com.aura.what2eat.service.FirebaseService
import com.aura.what2eat.service.GeminiAIService
import com.aura.what2eat.service.LocationService
import com.aura.what2eat.service.RECIPE_SUPPORTED_LANGUAGES
import com.aura.what2eat.service.RecipeTranslationService
import com.aura.what2eat.service.SupportedLanguage
import com.aura.what2eat.data.local.PreferencesManager
import com.aura.what2eat.ui.LocalSubscriptionManager
import com.aura.what2eat.ui.theme.*
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddSuggestionScreen(
    onNavigateBack: () -> Unit,
    onNavigateToSubscription: () -> Unit = {}
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val prefsManager = remember { PreferencesManager.getInstance(context) }

    val billingManager = LocalSubscriptionManager.current
    val isProUser by billingManager.isPro.collectAsStateWithLifecycle()
    val isPro = isProUser || com.aura.what2eat.BuildConfig.DEBUG

    var currentUser by remember { mutableStateOf(GoogleAuthManager.getCurrentUser()) }
    var isAuthLoading by remember { mutableStateOf(false) }

    var dishName by remember { mutableStateOf("") }
    var selectedCuisine by remember { mutableStateOf(CuisineType.PAKISTANI) }
    var isCheckingAI by remember { mutableStateOf(false) }
    var isAiGenerated by remember { mutableStateOf(false) }
    var recipeFound by remember { mutableStateOf<Boolean?>(null) }
    var recipeErrorMsg by remember { mutableStateOf<String?>(null) }
    var showPaywallDialog by remember { mutableStateOf(false) }

    // Moderation, Ban & Quotas (3 Free per day / Unlimited for PRO and Debug)
    var isUserBanned by remember { mutableStateOf(false) }
    var isCheckingBan by remember { mutableStateOf(false) }
    var canAddToday by remember { mutableStateOf(prefsManager.canAddSuggestionToday(isPro)) }
    var canGenerateRecipe by remember { mutableStateOf(prefsManager.canGenerateRecipeToday(isPro)) }
    var recipeGenRemaining by remember { mutableIntStateOf(prefsManager.getDailyRecipeGenerationsRemaining(isPro)) }
    var dailyCount by remember { mutableIntStateOf(prefsManager.getDailySuggestionCount()) }
    var recipeGenCount by remember { mutableIntStateOf(prefsManager.getDailyRecipeGenerationCount()) }
    var dailyLimit by remember { mutableIntStateOf(prefsManager.getDailySuggestionLimit(isPro)) }

    // Language selector for preview (English, Roman Urdu, Urdu, Hindi, Arabic, Spanish, Bengali)
    var rawEnglishIngredients by remember { mutableStateOf<List<String>>(emptyList()) }
    var rawEnglishSteps by remember { mutableStateOf<List<String>>(emptyList()) }
    var rawEnglishChefTip by remember { mutableStateOf("") }
    var selectedLanguage by remember { mutableStateOf(RECIPE_SUPPORTED_LANGUAGES[0]) }
    var isTranslating by remember { mutableStateOf(false) }

    LaunchedEffect(currentUser, isPro) {
        val user = currentUser
        canAddToday = prefsManager.canAddSuggestionToday(isPro)
        canGenerateRecipe = prefsManager.canGenerateRecipeToday(isPro)
        recipeGenRemaining = prefsManager.getDailyRecipeGenerationsRemaining(isPro)
        dailyCount = prefsManager.getDailySuggestionCount()
        recipeGenCount = prefsManager.getDailyRecipeGenerationCount()
        dailyLimit = prefsManager.getDailySuggestionLimit(isPro)

        if (user != null) {
            isCheckingBan = true
            isUserBanned = FirebaseService.isUserBanned(user.uid, user.email ?: "")
            isCheckingBan = false
        } else {
            isUserBanned = false
        }
    }

    // Recipe fields
    var ingredientsText by remember { mutableStateOf("") }
    var stepsText by remember { mutableStateOf("") }
    var prepTimeMinutes by remember { mutableIntStateOf(35) }
    var difficulty by remember { mutableStateOf("Medium") }
    var chefTip by remember { mutableStateOf("") }
    var isSubmitting by remember { mutableStateOf(false) }

    val difficulties = listOf("Easy", "Medium", "Hard")

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = "Add Dish Suggestion",
                        fontFamily = NunitoFontFamily,
                        fontWeight = FontWeight.Bold
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back"
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = BackgroundOffWhite)
            )
        },
        containerColor = BackgroundOffWhite
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp, vertical = 12.dp)
        ) {
            // Check Google Sign-In Status — Form only accessible when logged in
            if (currentUser == null) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 24.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(20.dp),
                        colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                        elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
                    ) {
                        Column(
                            modifier = Modifier.padding(24.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(60.dp)
                                    .background(PrimaryOrange.copy(alpha = 0.12f), shape = androidx.compose.foundation.shape.CircleShape),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Lock,
                                    contentDescription = "Lock",
                                    tint = PrimaryOrange,
                                    modifier = Modifier.size(32.dp)
                                )
                            }

                            Spacer(modifier = Modifier.height(16.dp))

                            Text(
                                text = "Sign in with Google to Submit",
                                fontFamily = NunitoFontFamily,
                                fontWeight = FontWeight.Bold,
                                fontSize = 20.sp,
                                color = DarkText,
                                textAlign = androidx.compose.ui.text.style.TextAlign.Center
                            )

                            Spacer(modifier = Modifier.height(6.dp))

                            Text(
                                text = "To ensure high quality recipes for the What2Eat community, you must be signed in with Google to share your dish suggestions.",
                                fontFamily = NunitoFontFamily,
                                fontSize = 13.sp,
                                color = TextMuted,
                                textAlign = androidx.compose.ui.text.style.TextAlign.Center
                            )

                            Spacer(modifier = Modifier.height(24.dp))

                            Button(
                                onClick = {
                                    isAuthLoading = true
                                    scope.launch {
                                        GoogleAuthManager.signIn(context).collect { result ->
                                            when (result) {
                                                is AuthResult.Success -> {
                                                    isAuthLoading = false
                                                    currentUser = result.user
                                                    val name = result.user.displayName ?: "Chef"
                                                    Toast.makeText(context, "Signed in as $name 🎉", Toast.LENGTH_SHORT).show()
                                                }
                                                is AuthResult.Error -> {
                                                    isAuthLoading = false
                                                    Toast.makeText(context, result.message, Toast.LENGTH_LONG).show()
                                                }
                                                is AuthResult.Loading -> {
                                                    isAuthLoading = true
                                                }
                                                else -> {}
                                            }
                                        }
                                    }
                                },
                                shape = RoundedCornerShape(14.dp),
                                colors = ButtonDefaults.buttonColors(containerColor = PrimaryOrange),
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(52.dp)
                            ) {
                                if (isAuthLoading) {
                                    CircularProgressIndicator(color = SurfaceWhite, modifier = Modifier.size(20.dp))
                                } else {
                                    Text(
                                        text = "Sign In with Google",
                                        fontFamily = NunitoFontFamily,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 16.sp,
                                        color = SurfaceWhite
                                    )
                                }
                            }
                        }
                    }
                }
            } else {
                // Logged-in User Profile Header
                Surface(
                    shape = RoundedCornerShape(12.dp),
                    color = SecondaryEmerald.copy(alpha = 0.12f),
                    border = androidx.compose.foundation.BorderStroke(1.dp, SecondaryEmerald.copy(alpha = 0.3f)),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(horizontal = 14.dp, vertical = 10.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(text = "👨", fontSize = 18.sp)
                            Spacer(modifier = Modifier.width(8.dp))
                            Column {
                                Text(
                                    text = "Submitting as: ${currentUser?.displayName ?: "Community Chef"}",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 13.sp,
                                    color = DarkText
                                )
                                if (!currentUser?.email.isNullOrBlank()) {
                                    Text(
                                        text = currentUser?.email ?: "",
                                        fontFamily = NunitoFontFamily,
                                        fontSize = 11.sp,
                                        color = TextMuted
                                    )
                                }
                            }
                        }

                        TextButton(
                            onClick = {
                                scope.launch {
                                    GoogleAuthManager.signOut(context)
                                    currentUser = null
                                }
                            }
                        ) {
                            Text(
                                text = "Switch Account",
                                fontFamily = NunitoFontFamily,
                                fontSize = 11.sp,
                                color = PrimaryOrange,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(16.dp))

                // Account Restriction Notice (if user received 5 community reports or violated rules)
                if (isUserBanned) {
                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(bottom = 16.dp),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = RedCancel.copy(alpha = 0.12f)),
                        border = androidx.compose.foundation.BorderStroke(1.5.dp, RedCancel.copy(alpha = 0.6f))
                    ) {
                        Row(
                            modifier = Modifier.padding(16.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Block,
                                contentDescription = "Blocked",
                                tint = RedCancel,
                                modifier = Modifier.size(32.dp)
                            )
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text(
                                    text = "Account Blocked",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp,
                                    color = RedCancel
                                )
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = "Your recipe was reported by 5 users or was not correct. You are blocked from uploading suggestions again, and all your old suggestions have been removed by the What2Eat Team.",
                                    fontFamily = NunitoFontFamily,
                                    fontSize = 13.sp,
                                    color = DarkText,
                                    lineHeight = 18.sp
                                )
                            }
                        }
                    }
                } else {
                    // Community Rule Warning Notice
                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(bottom = 16.dp),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = GoldProContainer.copy(alpha = 0.55f)),
                        border = androidx.compose.foundation.BorderStroke(1.2.dp, GoldPro.copy(alpha = 0.7f))
                    ) {
                        Row(
                            modifier = Modifier.padding(14.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Warning,
                                contentDescription = "Warning",
                                tint = GoldPro,
                                modifier = Modifier.size(28.dp)
                            )
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text(
                                    text = "Important Rule",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 13.sp,
                                    color = DarkText
                                )
                                Spacer(modifier = Modifier.height(2.dp))
                                Text(
                                    text = "If recipe is not correct or reported by any 5 users, then you will be blocked and cannot upload suggestions again, and your old suggestions will also be removed by What2Eat Team.",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.SemiBold,
                                    fontSize = 12.5.sp,
                                    color = DarkText,
                                    lineHeight = 18.sp
                                )
                            }
                        }
                    }
                }

                // Daily Limit Banner (3 Free Per Day, Unlimited for PRO / Debug)
                if (!isPro && (!canAddToday || !canGenerateRecipe)) {
                    val usedCount = maxOf(dailyCount, recipeGenCount)
                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(bottom = 16.dp),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = PrimaryOrange.copy(alpha = 0.12f)),
                        border = androidx.compose.foundation.BorderStroke(1.2.dp, PrimaryOrange.copy(alpha = 0.5f))
                    ) {
                        Row(
                            modifier = Modifier.padding(14.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Lock,
                                contentDescription = "Daily Limit",
                                tint = PrimaryOrange,
                                modifier = Modifier.size(28.dp)
                            )
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text(
                                    text = "Daily Limit Reached: $usedCount / 3 Free Generations Used",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 13.5.sp,
                                    color = DarkText
                                )
                                Spacer(modifier = Modifier.height(2.dp))
                                Text(
                                    text = "Free chefs can generate up to 3 recipes per day ($usedCount/3 used). Upgrade to PRO for unlimited recipe generations and dining suggestions!",
                                    fontFamily = NunitoFontFamily,
                                    fontSize = 12.sp,
                                    color = TextMuted,
                                    lineHeight = 16.sp
                                )
                            }
                        }
                    }
                }

                // Step 1: Dish Name & Cuisine
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(20.dp),
                    colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                    elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
                ) {
                    Column(
                        modifier = Modifier.padding(20.dp)
                    ) {
                    Text(
                        text = "1. Dish Information",
                        fontFamily = NunitoFontFamily,
                        fontWeight = FontWeight.Bold,
                        fontSize = 16.sp,
                        color = DarkText
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    OutlinedTextField(
                        value = dishName,
                        onValueChange = {
                            dishName = it
                            recipeFound = null
                            recipeErrorMsg = null
                        },
                        label = { Text("Dish Name (e.g. Mutton Handi)", fontFamily = NunitoFontFamily) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = PrimaryOrange,
                            unfocusedBorderColor = CardBorder
                        ),
                        singleLine = true,
                        enabled = !isUserBanned && canAddToday
                    )

                    Spacer(modifier = Modifier.height(14.dp))

                    Text(
                        text = "Cuisine Category",
                        fontFamily = NunitoFontFamily,
                        fontWeight = FontWeight.SemiBold,
                        fontSize = 13.sp,
                        color = TextMuted
                    )

                    Spacer(modifier = Modifier.height(8.dp))

                    LazyRow(
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        items(CuisineType.values()) { cuisine ->
                            val isSelected = (selectedCuisine == cuisine)
                            Surface(
                                shape = RoundedCornerShape(10.dp),
                                color = if (isSelected) PrimaryOrange else BackgroundOffWhite,
                                border = androidx.compose.foundation.BorderStroke(1.dp, if (isSelected) PrimaryOrange else CardBorder),
                                modifier = Modifier.clickable(enabled = !isUserBanned && canAddToday) { selectedCuisine = cuisine }
                            ) {
                                Text(
                                    text = cuisine.displayName,
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Medium,
                                    fontSize = 13.sp,
                                    color = if (isSelected) SurfaceWhite else DarkText,
                                    modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp)
                                )
                            }
                        }
                    }

                    Spacer(modifier = Modifier.height(16.dp))

                    // AI Auto-Fill Header & Daily Quota Info (3/day for Free, Unlimited for PRO / Debug)
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = "AI Recipe Generator",
                            fontFamily = NunitoFontFamily,
                            fontWeight = FontWeight.Bold,
                            fontSize = 13.sp,
                            color = DarkText
                        )
                        Text(
                            text = if (isPro) "PRO Active • Unlimited Generations ✨" else "$recipeGenRemaining of 3 generations left today",
                            fontFamily = NunitoFontFamily,
                            fontWeight = FontWeight.SemiBold,
                            fontSize = 11.5.sp,
                            color = if (isPro || recipeGenRemaining > 0) PrimaryOrange else RedCancel
                        )
                    }

                    Spacer(modifier = Modifier.height(6.dp))

                    // AI Auto-Fill Button (Locked when 3/day reached in free version)
                    val isGenerationAllowed = canGenerateRecipe && !isUserBanned
                    Button(
                        onClick = {
                            if (!canGenerateRecipe || recipeGenRemaining <= 0) {
                                showPaywallDialog = true
                                return@Button
                            }
                            if (isUserBanned) {
                                Toast.makeText(context, "You are blocked from adding suggestions due to community reports.", Toast.LENGTH_LONG).show()
                                return@Button
                            }
                            if (dishName.isBlank()) {
                                Toast.makeText(context, "Please enter a dish name first", Toast.LENGTH_SHORT).show()
                                return@Button
                            }
                            isCheckingAI = true
                            recipeErrorMsg = null
                            scope.launch {
                                val (_, country) = LocationService.getSavedLocation(context)
                                val resolvedCountry = country.ifBlank { "Pakistan" }
                                val aiDish = GeminiAIService.generateRecipe(
                                    dishName = dishName.trim(),
                                    cuisine = selectedCuisine.displayName,
                                    country = resolvedCountry
                                )
                                isCheckingAI = false
                                if (aiDish != null && aiDish.recipeSteps.isNotEmpty()) {
                                    prefsManager.recordRecipeGeneratedToday()
                                    recipeGenCount = prefsManager.getDailyRecipeGenerationCount()
                                    recipeGenRemaining = prefsManager.getDailyRecipeGenerationsRemaining(isPro)
                                    canGenerateRecipe = prefsManager.canGenerateRecipeToday(isPro)
                                    canAddToday = prefsManager.canAddSuggestionToday(isPro)

                                    rawEnglishIngredients = aiDish.ingredients
                                    rawEnglishSteps = aiDish.recipeSteps
                                    rawEnglishChefTip = aiDish.chefTip
                                    ingredientsText = aiDish.ingredients.joinToString("\n")
                                    stepsText = aiDish.recipeSteps.joinToString("\n")
                                    prepTimeMinutes = aiDish.prepTimeMinutes
                                    difficulty = aiDish.difficulty
                                    chefTip = aiDish.chefTip
                                    selectedLanguage = RECIPE_SUPPORTED_LANGUAGES[0]
                                    isAiGenerated = true
                                    recipeFound = true
                                    recipeErrorMsg = null
                                    com.aura.what2eat.service.LocalAiStorageService.saveGeneratedRecipeLocally(context, aiDish)
                                    val statusMsg = if (com.aura.what2eat.BuildConfig.DEBUG) " (Debug: AI API Active)" else ""
                                    Toast.makeText(context, "Recipe auto-filled by What2eat in English! ✨$statusMsg", Toast.LENGTH_SHORT).show()
                                } else {
                                    recipeFound = false
                                    recipeErrorMsg = "A.i don't understand this and cannot generate receipe kindly write your receipe correctly."
                                    val statusMsg = if (com.aura.what2eat.BuildConfig.DEBUG) " (Debug: AI API Offline/Unrecognized)" else ""
                                    Toast.makeText(context, "A.i don't understand this and cannot generate receipe kindly write your receipe correctly.$statusMsg", Toast.LENGTH_LONG).show()
                                }
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(
                            containerColor = if (isGenerationAllowed) PrimaryOrange.copy(alpha = 0.15f) else BackgroundOffWhite,
                            contentColor = if (isGenerationAllowed) PrimaryOrange else TextMuted
                        ),
                        enabled = !isCheckingAI
                    ) {
                        if (isCheckingAI) {
                            CircularProgressIndicator(modifier = Modifier.size(18.dp), color = PrimaryOrange)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "Checking AI for recipe...",
                                fontFamily = NunitoFontFamily,
                                fontWeight = FontWeight.Bold,
                                color = PrimaryOrange
                            )
                        } else if (!canGenerateRecipe || recipeGenRemaining <= 0) {
                            Icon(
                                imageVector = Icons.Default.Lock,
                                contentDescription = null,
                                tint = TextMuted,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "Recipe Generation Locked (3/3 Used Today)",
                                fontFamily = NunitoFontFamily,
                                fontWeight = FontWeight.Bold,
                                color = TextMuted
                            )
                        } else {
                            Icon(
                                imageVector = Icons.Default.AutoAwesome,
                                contentDescription = null,
                                tint = PrimaryOrange,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = if (isPro) "Auto-Fill Recipe with What2eat" else "Auto-Fill Recipe with What2eat ($recipeGenRemaining/3 left)",
                                fontFamily = NunitoFontFamily,
                                fontWeight = FontWeight.Bold,
                                color = PrimaryOrange
                            )
                        }
                    }

                    // Recipe Generation Feedback Banners
                    if (recipeFound == false && recipeErrorMsg != null) {
                        Spacer(modifier = Modifier.height(12.dp))
                        Surface(
                            shape = RoundedCornerShape(12.dp),
                            color = RedCancel.copy(alpha = 0.10f),
                            border = androidx.compose.foundation.BorderStroke(1.dp, RedCancel.copy(alpha = 0.4f)),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(
                                modifier = Modifier.padding(12.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Info,
                                    contentDescription = null,
                                    tint = RedCancel,
                                    modifier = Modifier.size(20.dp)
                                )
                                Spacer(modifier = Modifier.width(10.dp))
                                Text(
                                    text = recipeErrorMsg!!,
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.SemiBold,
                                    fontSize = 13.sp,
                                    color = RedCancel
                                )
                            }
                        }
                    } else if (recipeFound == true && isAiGenerated) {
                        Spacer(modifier = Modifier.height(12.dp))
                        Surface(
                            shape = RoundedCornerShape(12.dp),
                            color = SuccessGreen.copy(alpha = 0.12f),
                            border = androidx.compose.foundation.BorderStroke(1.dp, SuccessGreen.copy(alpha = 0.4f)),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(
                                modifier = Modifier.padding(12.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = null,
                                    tint = SuccessGreen,
                                    modifier = Modifier.size(20.dp)
                                )
                                Spacer(modifier = Modifier.width(10.dp))
                                Text(
                                    text = "Recipe generated in English! You can preview/translate below before submitting.",
                                    fontFamily = NunitoFontFamily,
                                    fontWeight = FontWeight.SemiBold,
                                    fontSize = 13.sp,
                                    color = DarkText
                                )
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Step 2: Recipe Form (Ingredients, Steps, Tips, Language Preview)
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(20.dp),
                colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(
                    modifier = Modifier.padding(20.dp)
                ) {
                    Text(
                        text = if (isAiGenerated) "2. Recipe Preview & Translation" else "2. Enter Recipe Details",
                        fontFamily = NunitoFontFamily,
                        fontWeight = FontWeight.Bold,
                        fontSize = 16.sp,
                        color = DarkText
                    )

                    // Language Selector Row (Allows user to read recipe in Roman Urdu, Urdu, Hindi, Arabic, etc.)
                    if (isAiGenerated || ingredientsText.isNotBlank()) {
                        Spacer(modifier = Modifier.height(10.dp))
                        Text(
                            text = "Read / Preview Recipe In:",
                            fontFamily = NunitoFontFamily,
                            fontWeight = FontWeight.SemiBold,
                            fontSize = 12.sp,
                            color = TextMuted
                        )
                        Spacer(modifier = Modifier.height(6.dp))
                        LazyRow(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                            items(RECIPE_SUPPORTED_LANGUAGES) { lang ->
                                val isSelected = (selectedLanguage.code == lang.code)
                                Surface(
                                    shape = RoundedCornerShape(8.dp),
                                    color = if (isSelected) PrimaryOrange else BackgroundOffWhite,
                                    border = androidx.compose.foundation.BorderStroke(1.dp, if (isSelected) PrimaryOrange else CardBorder),
                                    modifier = Modifier.clickable {
                                        if (selectedLanguage.code != lang.code) {
                                            selectedLanguage = lang
                                            if (lang.code == "en") {
                                                if (rawEnglishIngredients.isNotEmpty()) ingredientsText = rawEnglishIngredients.joinToString("\n")
                                                if (rawEnglishSteps.isNotEmpty()) stepsText = rawEnglishSteps.joinToString("\n")
                                                if (rawEnglishChefTip.isNotBlank()) chefTip = rawEnglishChefTip
                                            } else {
                                                scope.launch {
                                                    isTranslating = true
                                                    val currentIngr = if (rawEnglishIngredients.isNotEmpty()) rawEnglishIngredients else ingredientsText.split("\n").filter { it.isNotBlank() }
                                                    val currentSteps = if (rawEnglishSteps.isNotEmpty()) rawEnglishSteps else stepsText.split("\n").filter { it.isNotBlank() }
                                                    val currentTip = if (rawEnglishChefTip.isNotBlank()) rawEnglishChefTip else chefTip
                                                    val dishObj = Dish(
                                                        name = dishName.trim(),
                                                        ingredients = currentIngr,
                                                        recipeSteps = currentSteps,
                                                        chefTip = currentTip
                                                    )
                                                    val translated = RecipeTranslationService.translateRecipe(dishObj, lang)
                                                    ingredientsText = translated.ingredients.joinToString("\n")
                                                    stepsText = translated.steps.joinToString("\n")
                                                    if (translated.chefTip.isNotBlank()) {
                                                        chefTip = translated.chefTip
                                                    }
                                                    isTranslating = false
                                                }
                                            }
                                        }
                                    }
                                ) {
                                    Row(
                                        modifier = Modifier.padding(horizontal = 8.dp, vertical = 5.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Text(text = lang.flag, fontSize = 12.sp)
                                        Spacer(modifier = Modifier.width(4.dp))
                                        Text(
                                            text = lang.displayName,
                                            fontFamily = NunitoFontFamily,
                                            fontSize = 11.sp,
                                            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal,
                                            color = if (isSelected) SurfaceWhite else DarkText
                                        )
                                    }
                                }
                            }
                        }

                        if (isTranslating) {
                            Spacer(modifier = Modifier.height(6.dp))
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                CircularProgressIndicator(modifier = Modifier.size(12.dp), color = PrimaryOrange, strokeWidth = 1.5.dp)
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    text = "Translating recipe...",
                                    fontFamily = NunitoFontFamily,
                                    fontSize = 11.sp,
                                    color = PrimaryOrange
                                )
                            }
                        }
                    }

                    Spacer(modifier = Modifier.height(14.dp))

                    OutlinedTextField(
                        value = ingredientsText,
                        onValueChange = {
                            ingredientsText = it
                            if (selectedLanguage.code == "en") {
                                rawEnglishIngredients = it.split("\n").map { s -> s.trim() }.filter { s -> s.isNotBlank() }
                            }
                        },
                        label = { Text("Ingredients (one per line)", fontFamily = NunitoFontFamily) },
                        placeholder = { Text("500g Mutton\n2 Onions chopped\n1 tsp Garam Masala", color = TextMuted) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = PrimaryOrange,
                            unfocusedBorderColor = CardBorder
                        ),
                        minLines = 4,
                        enabled = !isUserBanned && canAddToday
                    )

                    Spacer(modifier = Modifier.height(14.dp))

                    OutlinedTextField(
                        value = stepsText,
                        onValueChange = {
                            stepsText = it
                            if (selectedLanguage.code == "en") {
                                rawEnglishSteps = it.split("\n").map { s -> s.trim() }.filter { s -> s.isNotBlank() }
                            }
                        },
                        label = { Text("Cooking Steps (numbered or one per line)", fontFamily = NunitoFontFamily) },
                        placeholder = { Text("1. Heat oil and brown the onions.\n2. Add ginger garlic and spices.\n3. Simmer until meat is tender.", color = TextMuted) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = PrimaryOrange,
                            unfocusedBorderColor = CardBorder
                        ),
                        minLines = 4,
                        enabled = !isUserBanned && canAddToday
                    )

                    Spacer(modifier = Modifier.height(14.dp))

                    // Prep Time & Difficulty
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        OutlinedTextField(
                            value = prepTimeMinutes.toString(),
                            onValueChange = { prepTimeMinutes = it.toIntOrNull() ?: 30 },
                            label = { Text("Prep Time (min)", fontFamily = NunitoFontFamily) },
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(12.dp),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedBorderColor = PrimaryOrange,
                                unfocusedBorderColor = CardBorder
                            ),
                            singleLine = true,
                            enabled = !isUserBanned && canAddToday
                        )

                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = "Difficulty",
                                fontFamily = NunitoFontFamily,
                                fontWeight = FontWeight.SemiBold,
                                fontSize = 12.sp,
                                color = TextMuted
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                difficulties.forEach { diff ->
                                    val isSelected = (difficulty == diff)
                                    Surface(
                                        shape = RoundedCornerShape(8.dp),
                                        color = if (isSelected) PrimaryOrange else BackgroundOffWhite,
                                        modifier = Modifier
                                            .weight(1f)
                                            .clickable(enabled = !isUserBanned && canAddToday) { difficulty = diff }
                                    ) {
                                        Text(
                                            text = diff,
                                            fontFamily = NunitoFontFamily,
                                            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Medium,
                                            fontSize = 11.sp,
                                            color = if (isSelected) SurfaceWhite else DarkText,
                                            textAlign = androidx.compose.ui.text.style.TextAlign.Center,
                                            modifier = Modifier.padding(vertical = 8.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }

                    Spacer(modifier = Modifier.height(14.dp))

                    OutlinedTextField(
                        value = chefTip,
                        onValueChange = {
                            chefTip = it
                            if (selectedLanguage.code == "en") {
                                rawEnglishChefTip = it.trim()
                            }
                        },
                        label = { Text("Chef's Pro Tip (Optional)", fontFamily = NunitoFontFamily) },
                        placeholder = { Text("e.g. Cook on low heat for maximum tenderness", color = TextMuted) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = PrimaryOrange,
                            unfocusedBorderColor = CardBorder
                        ),
                        singleLine = false,
                        minLines = 3,
                        maxLines = 6,
                        enabled = !isUserBanned && canAddToday
                    )
                }
            }

            Spacer(modifier = Modifier.height(18.dp))

            // Policy notice right above submit
            Text(
                text = "⚠️ If your recipe is not correct or reported by any 5 users, then you will be blocked and cannot upload suggestions again, and your old suggestions will also be removed by What2Eat Team.",
                fontFamily = NunitoFontFamily,
                fontWeight = FontWeight.Medium,
                fontSize = 11.5.sp,
                color = TextMuted,
                textAlign = androidx.compose.ui.text.style.TextAlign.Center,
                lineHeight = 16.sp,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 12.dp)
            )

            Spacer(modifier = Modifier.height(12.dp))

            // Submit Button
            Button(
                onClick = {
                    if (!prefsManager.canAddSuggestionToday(isPro)) {
                        Toast.makeText(context, "Daily limit reached: You can add only $dailyLimit suggestions per day. Please return tomorrow!", Toast.LENGTH_LONG).show()
                        return@Button
                    }
                    if (isUserBanned) {
                        Toast.makeText(context, "You are blocked from adding suggestions due to community reports.", Toast.LENGTH_LONG).show()
                        return@Button
                    }
                    if (dishName.isBlank()) {
                        Toast.makeText(context, "Please enter a dish name", Toast.LENGTH_SHORT).show()
                        return@Button
                    }
                    if (ingredientsText.isBlank() || stepsText.isBlank()) {
                        Toast.makeText(context, "Please provide ingredients and steps", Toast.LENGTH_SHORT).show()
                        return@Button
                    }

                    val (_, country) = LocationService.getSavedLocation(context)

                    // Always ensure the uploaded recipe to Firebase is in English
                    val uploadIngredients = if (rawEnglishIngredients.isNotEmpty()) {
                        rawEnglishIngredients
                    } else {
                        ingredientsText.split("\n").map { it.trim() }.filter { it.isNotBlank() }
                    }

                    val uploadSteps = if (rawEnglishSteps.isNotEmpty()) {
                        rawEnglishSteps
                    } else {
                        stepsText.split("\n").map { it.trim() }.filter { it.isNotBlank() }
                    }

                    val uploadChefTip = if (rawEnglishChefTip.isNotBlank()) {
                        rawEnglishChefTip.trim()
                    } else {
                        chefTip.trim()
                    }

                    val communityDish = CommunityDish(
                        id = "cd_${System.currentTimeMillis()}",
                        dishName = dishName.trim(),
                        submittedBy = currentUser?.displayName ?: "Community Chef",
                        userEmail = currentUser?.email ?: "",
                        userUID = currentUser?.uid ?: "",
                        cuisine = selectedCuisine.displayName,
                        country = country,
                        likesCount = 0,
                        reportCount = 0,
                        ingredients = uploadIngredients,
                        recipeSteps = uploadSteps,
                        prepTime = prepTimeMinutes,
                        difficulty = difficulty,
                        chefTip = uploadChefTip,
                        isAIGenerated = isAiGenerated,
                        createdAt = System.currentTimeMillis(),
                        isApproved = true,
                        isBlocked = false
                    )

                    isSubmitting = true
                    scope.launch {
                        val success = FirebaseService.submitSuggestion(communityDish)
                        isSubmitting = false
                        if (success) {
                            prefsManager.recordSuggestionAddedToday()
                            canAddToday = prefsManager.canAddSuggestionToday(isPro)
                            canGenerateRecipe = prefsManager.canGenerateRecipeToday(isPro)
                            recipeGenRemaining = prefsManager.getDailyRecipeGenerationsRemaining(isPro)
                            dailyCount = prefsManager.getDailySuggestionCount()
                            recipeGenCount = prefsManager.getDailyRecipeGenerationCount()
                            Toast.makeText(context, "Recipe submitted successfully! 🎉", Toast.LENGTH_LONG).show()
                            onNavigateBack()
                        } else {
                            if (isUserBanned) {
                                Toast.makeText(context, "You are blocked from adding suggestions due to community reports.", Toast.LENGTH_LONG).show()
                            } else {
                                Toast.makeText(context, "Failed to submit. Please try again.", Toast.LENGTH_SHORT).show()
                            }
                        }
                    }
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(54.dp),
                shape = RoundedCornerShape(16.dp),
                colors = ButtonDefaults.buttonColors(containerColor = PrimaryOrange),
                enabled = !isSubmitting && !isUserBanned && !isCheckingBan && canAddToday
            ) {
                if (isSubmitting) {
                    CircularProgressIndicator(color = SurfaceWhite, modifier = Modifier.size(20.dp))
                } else {
                    Icon(imageVector = Icons.Default.Check, contentDescription = null, tint = SurfaceWhite)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = if (!canAddToday) "Daily Limit Reached ($dailyCount/$dailyLimit Used)" else "Submit Recipe to Community",
                        fontFamily = NunitoFontFamily,
                        fontWeight = FontWeight.Bold,
                        fontSize = 16.sp,
                        color = SurfaceWhite
                    )
                }
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
        }
    }

    // Paywall Dialog when 3/day free recipe generations are exhausted
    if (showPaywallDialog) {
        AlertDialog(
            onDismissRequest = { showPaywallDialog = false },
            icon = {
                Icon(
                    imageVector = Icons.Default.AutoAwesome,
                    contentDescription = null,
                    tint = PrimaryOrange,
                    modifier = Modifier.size(32.dp)
                )
            },
            title = {
                Text(
                    text = "Daily Limit Reached",
                    fontFamily = NunitoFontFamily,
                    fontWeight = FontWeight.Bold,
                    fontSize = 18.sp,
                    color = DarkText
                )
            },
            text = {
                Text(
                    text = "You have used all 3 free recipe generations with What2eat for today. Upgrade to What2Eat PRO for unlimited recipe generations, unlimited dining suggestions, and full meal planner access!",
                    fontFamily = NunitoFontFamily,
                    fontSize = 14.sp,
                    color = DarkText
                )
            },
            confirmButton = {
                Button(
                    onClick = {
                        showPaywallDialog = false
                        onNavigateToSubscription()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = PrimaryOrange),
                    shape = RoundedCornerShape(10.dp)
                ) {
                    Text("Upgrade to PRO", fontFamily = NunitoFontFamily, fontWeight = FontWeight.Bold)
                }
            },
            dismissButton = {
                TextButton(onClick = { showPaywallDialog = false }) {
                    Text("Maybe Later", fontFamily = NunitoFontFamily, color = TextMuted)
                }
            },
            containerColor = SurfaceWhite,
            shape = RoundedCornerShape(16.dp)
        )
    }
}
