package com.aura.what2eat.service

import android.content.Context
import android.util.Log
import com.aura.what2eat.model.CuisineType
import com.aura.what2eat.model.DayType
import com.aura.what2eat.model.Dish
import com.aura.what2eat.model.MealType
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

object LocalAiStorageService {

    private const val TAG = "LocalAiStorageService"
    private const val SAVED_DISHES_FILE = "saved_ai_dishes.json"
    private const val SAVED_RECIPES_FILE = "saved_ai_recipes.json"

    private val gson = Gson()
    private val inMemoryDishCache = mutableListOf<Dish>()
    private val inMemoryRecipeCache = mutableMapOf<String, Dish>()
    private var isInitialized = false

    fun init(context: Context) {
        if (isInitialized) return
        try {
            val dishesFile = File(context.filesDir, SAVED_DISHES_FILE)
            if (dishesFile.exists()) {
                val json = dishesFile.readText(Charsets.UTF_8)
                val type = object : TypeToken<List<Dish>>() {}.type
                val list: List<Dish>? = gson.fromJson(json, type)
                if (!list.isNullOrEmpty()) {
                    synchronized(inMemoryDishCache) {
                        inMemoryDishCache.clear()
                        inMemoryDishCache.addAll(list)
                    }
                    Log.d(TAG, "Loaded ${list.size} saved AI dishes from local storage")
                }
            }

            val recipesFile = File(context.filesDir, SAVED_RECIPES_FILE)
            if (recipesFile.exists()) {
                val json = recipesFile.readText(Charsets.UTF_8)
                val type = object : TypeToken<Map<String, Dish>>() {}.type
                val map: Map<String, Dish>? = gson.fromJson(json, type)
                if (!map.isNullOrEmpty()) {
                    synchronized(inMemoryRecipeCache) {
                        inMemoryRecipeCache.clear()
                        inMemoryRecipeCache.putAll(map)
                    }
                    Log.d(TAG, "Loaded ${map.size} saved AI recipes from local storage")
                }
            }
            isInitialized = true
        } catch (e: Exception) {
            Log.e(TAG, "Error initializing LocalAiStorageService", e)
        }
    }

    /**
     * Saves newly generated AI dishes into local persistent file for offline/fallback use.
     */
    fun saveGeneratedDishesLocally(context: Context, newDishes: List<Dish>) {
        if (newDishes.isEmpty()) return
        try {
            init(context)
            synchronized(inMemoryDishCache) {
                for (dish in newDishes) {
                    if (inMemoryDishCache.none { it.name.trim().equals(dish.name.trim(), ignoreCase = true) }) {
                        inMemoryDishCache.add(0, dish)
                    }
                }
                // Keep up to 500 recent AI generated dishes locally
                val trimmed = if (inMemoryDishCache.size > 500) inMemoryDishCache.take(500) else inMemoryDishCache
                val file = File(context.filesDir, SAVED_DISHES_FILE)
                file.writeText(gson.toJson(trimmed), Charsets.UTF_8)
            }
            Log.d(TAG, "Saved ${newDishes.size} dishes locally. Total saved: ${inMemoryDishCache.size}")
        } catch (e: Exception) {
            Log.e(TAG, "Failed saving generated dishes locally", e)
        }
    }

    /**
     * Saves a full recipe generated by AI locally.
     */
    fun saveGeneratedRecipeLocally(context: Context, dish: Dish) {
        if (dish.name.isBlank()) return
        try {
            init(context)
            val key = dish.name.trim().lowercase()
            synchronized(inMemoryRecipeCache) {
                inMemoryRecipeCache[key] = dish
                val file = File(context.filesDir, SAVED_RECIPES_FILE)
                file.writeText(gson.toJson(inMemoryRecipeCache), Charsets.UTF_8)
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed saving recipe locally for ${dish.name}", e)
        }
    }

    /**
     * Retrieves saved AI dishes matching meal criteria when AI/API is offline.
     */
    fun getSavedAiSuggestions(
        country: String,
        mealType: MealType?,
        dayType: DayType?,
        excludedDishes: List<String>,
        wantToCook: List<String>,
        dontWantToCook: List<String>
    ): List<Dish> {
        val excludedLower = excludedDishes.map { it.trim().lowercase() }.toSet()
        val dontWantLower = dontWantToCook.map { it.trim().lowercase() }.toSet()

        synchronized(inMemoryDishCache) {
            return inMemoryDishCache.filter { dish ->
                val nameLower = dish.name.trim().lowercase()
                if (excludedLower.contains(nameLower)) return@filter false
                if (dontWantLower.any { nameLower.contains(it) }) return@filter false

                val countryMatch = country.isBlank() || dish.country.equals(country, ignoreCase = true) || dish.country.isBlank()
                val mealMatch = mealType == null || dish.mealType == mealType
                val dayMatch = dayType == null || dish.dayType == dayType

                countryMatch && mealMatch && dayMatch
            }
        }
    }

    /**
     * Gets a saved recipe if previously generated.
     */
    fun getSavedRecipeLocally(dishName: String): Dish? {
        val key = dishName.trim().lowercase()
        synchronized(inMemoryRecipeCache) {
            return inMemoryRecipeCache[key]
        }
    }
}
